version: '2'
services:
  rrhh2-app:
    image: rrhh2
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://rrhh2-mysql:3306/rrhh2?useUnicode=true&characterEncoding=utf8&useSSL=false'
      - JHIPSTER_SLEEP=30
    ports:
      - '8080:8080'
  rrhh2-mysql:
    image: 'mysql:8.0.17'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=rrhh2
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
